name: Audio Generation

on:
  workflow_dispatch:
    inputs:
      chapter_number:
        description: 'Chapter number to process'
        required: false
        default: ''
jobs:
  generate_audio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install edge-tts pydub deep-translator python-telegram-bot==20.6
      
      - name: Clean text for audio generation
        run: |
          python scripts/clean_data.py "${{ github.event.inputs.chapter_number }}"

      - name: Run audio generator
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python scripts/audio_gen.py "${{ github.event.inputs.chapter_number }}"
      
      - name: Commit updated processed list
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add processed_audio.txt
          git commit -m "Update processed_audio list"
          git push
          
