name: ChatTTS Full Setup and Verify

on:
  workflow_dispatch:
    inputs:
      chapter_number:
        description: 'Chapter number to process'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  run_chattts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    # - name: Free up disk space
    #   run: |
    #       sudo apt-get clean
    #       sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc \
    #         /usr/local/share/boost /usr/local/share/chromium /usr/share/swift \
    #         /usr/local/graalvm /opt/hostedtoolcache/CodeQL
    #       docker system prune -af || true
    #       sudo rm -rf /var/lib/mysql /var/lib/postgresql
    #       sudo rm -rf /tmp/*
    #       sudo rm -rf $HOME/.cargo
    #       sudo rm -rf $HOME/.gem
    #       sudo rm -rf $HOME/.rustup
    #       sudo rm -rf $HOME/.nvm
    #       sudo rm -rf $HOME/.npm
    #       sudo rm -rf $HOME/.gradle


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          python-version: "3.10"

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch pyyaml pydub deep-translator python-telegram-bot==20.6
        git clone https://github.com/resemble-ai/chatterbox.git
        cd chatterbox
        pip install -e .


    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Clean text for audio generation
      run: |
          python scripts/clean_data.py "${{ github.event.inputs.chapter_number }}"

      
    - name: Run ChatTTS inference and save output
      env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
          python scripts/chatt_audio_gen.py "${{ github.event.inputs.chapter_number }}"

      # run: |
      #   python << 'EOF'

      #   import torchaudio as ta
      #   from chatterbox.tts import ChatterboxTTS
      #   AUDIO_PROMPT_PATH="female_random_podcast.wav"

      #   model = ChatterboxTTS.from_pretrained(device="cpu")

      #   text = "Ezreal and Jinx teamed up with Ahri, Yasuo, and Teemo to take down the enemy's Nexus in an epic late-game pentakill."
      #   wav = model.generate(text)
      #   ta.save("test-1.wav", wav, model.sr)

      #   # If you want to synthesize with a different voice, specify the audio prompt
      #   #AUDIO_PROMPT_PATH = "YOUR_FILE.wav"
      #   wav = model.generate(text, audio_prompt_path=AUDIO_PROMPT_PATH)
      #   ta.save("test-2.wav", wav, model.sr)


      #   EOF

    - name: Commit updated processed list
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"          git add audio_done.txt
        git commit -m "Update processed_audio list"
        git push
        
