name: CosyVoice2 TTS (M1 self-hosted)

on:
  workflow_dispatch:

jobs:
  cosyvoice2-job:
    runs-on: macos-latest  # your Mac M1 registered as a runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (venv + PyTorch + CosyVoice)
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          # On macOS arm64, pip's default torch wheel includes Metal (MPS) support
          pip install torch torchvision torchaudio
          pip install cosyvoice soundfile
          pip install funasr==1.1.9 soundfile
     
      - name: Install system deps
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install ffmpeg
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y ffmpeg
          fi
        shell: bash

      - name: Install ffmpeg
        run: brew install ffmpeg



      - name: Run CosyVoice2 TTS
        shell: bash
        env:
          PYTORCH_ENABLE_MPS_FALLBACK: "1"
        run: |
          source .venv/bin/activate
          python run_tts.py "Hello, this is CosyVoice2 running on a Mac M1 self-hosted runner."

      - name: Upload generated audio
        uses: actions/upload-artifact@v4
        with:
          name: tts-audio
          path: output.wav
          if-no-files-found: error
