name: Docker Setup and Verify

on:
  workflow_dispatch:
    inputs:
      chapter_number:
        description: 'Chapter number to process'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  run_chattts:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          python-version: "3.10"
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run docker build
      run: |
         docker build -t zonos-runner:latest .
         #echo $GIT_GH | docker login ghcr.io -u rachel1hen --password-stdin --no-tty
         
         docker tag zonos-runner:latest ghcr.io/rachel1hen/pollinatio/zonos-runner:latest
         docker push ghcr.io/rachel1hen/pollinatio/zonos-runner:latest
         
         
         
